language: node_js
node_js:
  - "7"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always